### ISSUE TITLE
Improve Overall Documentation

### ISSUE THREAD

**Issue by SarojWasti** [Py-Contributors/audiobook#11]
Want to improve documentation to make it look like more professional. As of now there are some grammar and casing mistakes.

**Comment by codePerfectPlus** [comment]
that will be great.

**Comment by codePerfectPlus** [comment]
you can copy #contributors heading from this repo by changing repo link.
https://github.com/codePerfectPlus/RandomProfileGenerator

**Comment by SarojWasti** [comment]
You mean to add contributors section on Readme.md?

**Comment by codePerfectPlus** [comment]
> You mean to add contributors section on Readme.md?

Yes, it will look good
