### ISSUE TITLE
Voice: text to speech

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AudioBook#15]
**Is your feature request related to a problem? Please describe.**

Currently, There is one default voice for reading the book. There should also be an option for the user to select the other voice respective to their os platform.

**Comment by luminousbeam** [comment]
Hello there, I'm interested in working on this. Would you assign it to me?

**Comment by luminousbeam** [comment]
HI there, I apologize for the delay. A lot of new things have been put on my plate and I will not be able to complete this issue at this time. I am un-assigning myself as to allow anyone else who wants to tackle this to do so.
