### ISSUE TITLE
Support: add support to read/save web articles(audio)

### ISSUE THREAD

**Issue by codePerfectPlus** [Py-Contributors/audiobook#18]
adding support to read/save web articles in audio format

**Comment by giovf96** [comment]
Hi! 

Can I get this issue assigned to me? 
Thanks!

**Comment by codePerfectPlus** [comment]
can you give me some idea of how will you do it? Like a web page may have unnecessary text.

**Comment by giovf96** [comment]
> can you give me some idea of how will you do it? Like a web page may have unnecessary text.

I was thinking to take all the `<article>` tags in a web page using the [beautifulsoup library](https://www.crummy.com/software/BeautifulSoup/bs4/doc/).

Then, we can retrieve all the text tags in the DOM tree to make them playable with `pyttsx3`

**Comment by codePerfectPlus** [comment]
Happy Hacktoberfest and best of luck

**Comment by giovf96** [comment]
Thanks :) 
I've just opened here a [pull request](https://github.com/Py-Contributors/audiobook/pull/20)
