### ISSUE TITLE
Feature: `docs/docx` file support adding

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AudioBook#33]
**Is your feature request related to a problem? Please describe.**
Adding `Doc/Docx`  file support for audiobooks.

**Describe the solution you'd like**
I will use the docs2txt library to read docs files in python. 

**Describe alternatives you've considered**
Have to find any other library if there is one.

**Additional context**

**Comment by aaaandrzej** [comment]
Happy to be assigned there, PR in review now.
