### ISSUE TITLE
Bug Issue

### ISSUE THREAD

**Issue by TimTemi** [Py-Contributors/AudioBook#39]
![Screenshot_20221020-070750](https://user-images.githubusercontent.com/93915253/196869652-8adbc8e3-552d-40ff-81e5-b043ac3c020d.png)
![Screenshot_20221020-070758](https://user-images.githubusercontent.com/93915253/196869683-11535c6e-3c7b-4d60-8009-c3dd9bbf593d.png)

**Comment by codeperfectplus** [comment]
that's not a bug. It's a python linting error. Python has some code guidelines. code should be in that format. 
we are in the development phase now so we are ignoring it for now. we will update the code base with guidelines when the development phase will complete. 
@TimTemi

**Comment by TimTemi** [comment]
@codePerfectPlus Alright.
