### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by aaaandrzej** [Py-Contributors/AudioBook#42]
**Is your feature request related to a problem? Please describe.**
It's not clear now how one should run the script, CLI method and relevant "Usage" part in README would be useful

**Describe the solution you'd like**
`click` could be used - up to an author and maintainers

**Describe alternatives you've considered**
`sys.argv` is an alternative

**Additional context**
N/A

**Comment by codeperfectplus** [comment]
There are a lot of arguments, click won't look good. Have to add multiple decorators. argparse will be a good choice. It is also python-built in module.
will it also change how we call inside a python file?

**Comment by aaaandrzej** [comment]
I'm happy with either of these so sure, standard library is OK too. My expectation would be that nothing changes with existing execution options, CLI should be added on top of that.
