### ISSUE TITLE
Bug: PyPf2 missed words some times

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AudioBook#44]
**Describe the bug**
PyPdf2 sometimes misses the words. PDFMinor is Better than text extracting than PyPDF2. So will be adding support for Pdfminor. 
User can choose which engine he/she wants to select. the default will be Pdfminor. 

PDFMiner – This library is used to extract useful information from PDF documents. Unlike other tools, the entire focus of this package is to get and analyze the data.

PyPDF2 – This is a PDF library made of pure Python that can harvest, split, transform, and merge PDFs together.

**Expected behavior**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by codePerfectPlus** [comment]
fixed in recent PR #35
