### ISSUE TITLE
support: ODT file support adding

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AudioBook#46]
**Is your feature request related to a problem? Please describe.**

Audiobook doesn't support ODT file format yet. So creating a feature request for ODT file request. A file with the “.odt” extension is an OpenOffice Document file. It's a common file type in Linux.

@DrakeEntity

**Comment by Mr-vabs** [comment]
Assign this to me

**Comment by Mr-vabs** [comment]
Assign this to me
