### ISSUE TITLE
Bug: Fix documentation at Read the Docs site

### ISSUE THREAD

**Issue by aaaandrzej** [Py-Contributors/AudioBook#49]
**Describe the bug**
Documentation at linked Read the Docs site does not show actual readme

**To Reproduce**
Go to https://github.com/Py-Contributors/AudioBook#documentation and click the link, it redirects to an empty page at https://audiobook.readthedocs.io/

**Expected behavior**
This site is normally autogenerated, it says: "Please create an index.rst or README.rst file with your own content under the root (or /docs) directory in your repository.". Ideally such file should be created (or the link removed to avoid confusion).

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by codeperfectplus** [comment]
It was working before but it broke. I have to check my account log and why it's broke. Thanks for pointing out the issue.

**Comment by codeperfectplus** [comment]
I have fixed this issue. but need to update the documentation inside the docs folder. @aaaandrzej

**Comment by codeperfectplus** [comment]
will make more details documentation on readthedocs after this development work.

**Comment by DrakeEntity** [comment]
I have created an issue for that.

**Comment by codeperfectplus** [comment]
Thanks @DrakeEntity

**Comment by aaaandrzej** [comment]
I guess in this case this one can be closed as a duplicate of [#50]

**Comment by DrakeEntity** [comment]
So I have created more details PR. you can add details if there is anything missing. So both issues are different.

1. Documentation has a wrong link for reading the Docs site
2. Extend the documentation.

Thanks

**Comment by aaaandrzej** [comment]
@DrakeEntity you're right that these are different although I think I wasn't precise enough in my issue here. The link actually works, it redirects to relevant RTD site correctly. The actual problem is that this repo is missing the `rst` file based on which RTD autogenerates the site. Side question is if there was ever such file and got removed? @codePerfectPlus you said it used to work - do you recall how?

**Comment by DrakeEntity** [comment]
@aaaandrzej 
so `Readthedocs` has two types of documentation type.

1. MKdocs
2. Sphinx

By default, Sphinx requires `rst` file. It was previously set on Sphinx mode. `rst` file is not required we are using mkdocs.
but we are thinking to move the Sphinx documentation type. with the help of `Sphinx` we can have more detailed documentation.

**Comment by codeperfectplus** [comment]
yup, so By mistake, I set it to Sphinx. I changed back to Mkdocs. It's working now
