### ISSUE TITLE
extending the current documentation for readthedocs

### ISSUE THREAD

**Issue by DrakeEntity** [Py-Contributors/AudioBook#50]
**Is your feature request related to a problem? Please describe.**

Current Documentation is not sufficient. we have to extend it.  

**Plan for Docs**

will use Sphinx[¶](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#getting-started-with-sphinx) for documentation and write proper multipage documentation. 

**why multipage documentaion**

The current one-page documentation is messy. so we can divide it into easy components and extend the documentation. so it can be clearly explained in detail. 

**Proposed Pages of site**

1. Introduction
2. Installation
2. Use as a module
4. Use as a command line tool (save/read audiobook)
5. Upcoming changes
6. common problems while installing on Linux

This issue is open to assigning.

Branch:- https://github.com/Py-Contributors/AudioBook/tree/docs

Reference:-

https://pypdf2.readthedocs.io/en/latest/
https://flask.palletsprojects.com/en/2.2.x/

**Comment by codeperfectplus** [comment]
The first draft of the audiobook is complete. #68
