### ISSUE TITLE
[DOCS] Broken Badges

### ISSUE THREAD

**Issue by Akshu-on-github** [Py-Contributors/AudioBook#59]
**Broken Badges**
I'd suggest either removing the broken badges from the docs .md file or replacing the badges with static ones. The reason that this bug is happening is that `Shields.io` uses a `Pipfile.lock` to determine the version and dependencies - and this repo lacks the same.

![image](https://user-images.githubusercontent.com/61582763/198065185-239c8df6-f56e-4429-846d-581ffa44e108.png)

**Comment by codeperfectplus** [comment]
Thanks for pointing it out. Those shields are from the previous repo when I used to use pipefile. 😅 
I think I am a very lazy programmer.

**Comment by Akshu-on-github** [comment]
Oh, it happens to the best of us!
