### ISSUE TITLE
Text highlighting

### ISSUE THREAD

**Issue by TimTemi** [Py-Contributors/AudioBook#7]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am looking for a particular text and I have go line by line to find what I am looking for.

**Describe the solution you'd like**
I want to contribute a highlighting a new feature to the PDF reader, where I can easily highlight a text and it highlight all text in the PDF.

**Describe alternatives you've considered**
Pretty much reading the whole PDF, which is not time managing.

@codePerfectPlus , Please assign this issue to me, so I can work on it and contribute.

**Comment by TimTemi** [comment]
@codePerfectPlus , I need your approval to go ahead.

**Comment by codeperfectplus** [comment]
@TimTemi Are you working on the issue or show I assign myself? Please confirm the status

**Comment by TimTemi** [comment]
@codePerfectPlus, I am sorry for the delay, I am working on it and will commit pretty soon. Thanks.

**Comment by codeperfectplus** [comment]
No issues, I was just confirming. So currently the code base is changed. Now more file formats are supported and we are converting input books in common json format(page number: text) so please make sure to git pull.

**Comment by TimTemi** [comment]
@codePerfectPlus Alright, Noted.
