### ISSUE TITLE
There is an error in the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ezinneanne** [Py-Contributors/AudioBook#79]
**Short introduction what you want to change in README.md **
In the Contributing.md file, there is `git pull upstream master`.
This is wrong as the name of the main branch is `dev` and not `master`.
Also, there should be `git add` before `git commit`. This is because, as this project is open to everyone including beginners, it would be helpful to add all the necessary details.

**Comment by codeperfectplus** [comment]
Thanks for pointing out the issue.
