### ISSUE TITLE
support: adding RTF file support 

### ISSUE THREAD

**Issue by Suvoo** [Py-Contributors/AudioBook#82]
**Is your feature request related to a problem? Please describe.**
Audiobook doesn't support the RTF file format yet. So creating a feature request for RTF file request. A file with the “.rtf” extension is an OpenOffice Document file. It's a common file type in Linux and used as a substitute to .doc, very helpful in converting to PDF as well.
@codeperfectplus

**Comment by codeperfectplus** [comment]
would you like to work on it?

**Comment by Suvoo** [comment]
Yea sure! I will get onto it and file a PR :)

**Comment by codeperfectplus** [comment]
#83 merged
